# Configurations for GitHub Dependabot

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
    open-pull-requests-limit: 7
    rebase-strategy: "disabled"
