# Configurations for GitHub Dependabot

version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"
    milestone: 4
    open-pull-requests-limit: 7
