language: node_js
node_js:
  - node
  - 8
os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
env:
  - TARGET_ARCH=x64

cache:
  npm: true
  directories:
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

# restrict Travis-CI builds to specific branches only
# branches:
#   only:
#   - master
#   - /^v\d+\.\d+\.\d+/

before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
- yarn install
- yarn upgrade

script:
- yarn lint
- if test -z "$TRAVIS_TAG"; then yarn make; fi
after_success: if test -n "$TRAVIS_TAG"; then yarn publish; fi