name: Build Check

on: [pull_request, workflow_dispatch, workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Synectic
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: |
            package.json
            out/
            types/
          if-no-files-found: error

      # Add test steps here