name: Deploy to GitHub Pages

on: 
  push:
    tags:
      - '*' # Push events to all tags
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
jobs:
  build:
    uses: ./.github/workflows/build.yml
  bump:
    uses: ./.github/workflows/bump.yml
  deploy:
    needs: [build, bump]
    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        
      - name: Download macOS ARM build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-aarch64
          path: ./artifacts
          
      - name: Download macOS AMD64 build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-amd64
          path: ./artifacts
          
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: build-windows-amd64
          # Windows is not in a tarball, so we extract to a separate directory.
          path: ./artifacts/windows
          
      - name: Download Linux AMD64 build
        uses: actions/download-artifact@v3
        with:
          name: build-linux-amd64
          path: ./artifacts          
        
      - name: Run Conveyor
        if: github.event_name == 'push'
        uses: hydraulic-software/conveyor/actions/build@v11.4
        env:
          OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1