name: Deploy to GitHub Pages

on: 
  push:
    tags:
      - '*' # Push events to all tags
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
jobs:
  build:
    name: Build Check
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        
      - name: Run Conveyor
        if: github.event_name == 'push'
        uses: hydraulic-software/conveyor/actions/build@v11.4
        env:
          OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1