name: Deploy to GitHub Pages

on: 
  push:
    tags:
      - '*' # Push events to all tags
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  deploy:
    name: Deploy to GitHub Pages
    needs: [build]
    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-result
          path: ./artifacts
        
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v11.4
        env:
          # secrets.GITHUB_TOKEN is automatically set up by GitHub
          OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1