name: Node Continuous Integration

on:
  pull_request:
    branches: [ development ]
    
jobs:
  test_pull_request:
    if: github.event.pull_request.draft == 'false'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test
