name: Production Test Check
on:
  pull_request:
    branches: [ $default-branch ]
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  initial_state:
    runs-on: macos-latest
    env:
      DRAFT_STATE: ${{ github.event.pull_request.draft == false }}
    steps:
      - name: Draft State
        run: echo ${{ DRAFT_STATE }}
  test_pull_request:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ['14', '16']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        # See security recommendations for Yarn 2 at https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
        run: yarn ci:install
      - name: Run linting rules
        run: yarn lint
      - name: Run tests
        run: yarn test
