name: Releases

on:
  push:
    tags: 
    - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true  

jobs:
  release:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get package version
      id: get_version
      uses: daschaa/package-version@v1.1.0
      with:
        path: './package.json'
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn ci
    - run: yarn make
    - name: Create ${{ github.ref_name }} release on ${{ matrix.os }}
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "out/make/**"
        token: ${{ secrets.GITHUB_TOKEN }}