name: Release
on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app and uploads to GitHub Pages'
        default: false
        required: false
        type: boolean

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: 'bash'


jobs:
  draft_release:

    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
    # Important: Conveyor must be run from Linux.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - run: yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: yarn build

      - name: Release Agent
        run: echo "Release Agent"

      # - name: Run Conveyor
      #   uses: hydraulic-software/conveyor/actions/build@v11.4
      #   env:
      #     # secrets.GITHUB_TOKEN is automatically setup by GitHub
      #     OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     command: make copied-site
      #     extra_flags: -f ci.conveyor.conf
      #     signing_key: ${{ secrets.SIGNING_KEY }}
      #     agree_to_license: 1
