name: Releases

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get package version
        id: get_version
        uses: daschaa/package-version@v1.1.0
        with:
          path: './package.json'
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn make
      - name: Create ${{ github.ref_name }} release on ${{ matrix.os }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          omitBodyDuringUpdate: true
          artifacts: 'out/make/**'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Store release version (stripping any v-prefix)
        run: |
          VERSION = ${{ github.ref_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      - name: Repository Dispatch to https://nomatic.dev/synectic
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: nelsonni/website
          event-type: release
          client-payload: '{"version": "${{ github.ref_name }}", "raw_version": "${VERSION}"}'
