name: Releases

on:
  push:
    tags: 
    - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get package version
      id: get_version
      uses: daschaa/package-version@v1.1.0
      with:
        path: './package.json'
    - name: Output package version
      run: echo "The package version is ${{ steps.get_version.outputs.current-version }}"
    # - name: Create ${{ github.ref_name }} release on ${{ matrix.os }}
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "out/make/Synectic-${{ steps.get_version.outputs.current-version }}"
    #     generateReleaseNotes: true
    #     token: ${{ secrets.GITHUB_TOKEN }}